/*
	The C++ programming
	-------------------

c:=
	c is a programming language

	programming: set of instruction (method)
	program: instruction

	programming language
	--------------------

	1) lower level
		- computer frinedly
			- algol, bcpl.....

	2) middle level
		- computer & user friendly
			- c, c++............

	3) heigher level
		- user frinedly
			- java .net......

	c is a POP language

	POP: Procedure Oriented Programming

	ex:
		1   4     1
		2   3     3
		3   2     4
		4   1


c++: brajne stroupstup - in bell lab. - in 1989

	C++ is a OOP language

	OOP : Object Oriented Programming

	ex:

			study table ---> class
			-----------

	c:			c++:

	c                     i     j      k-----> object
	c                     c    c++    java
	c++                   c    c++    java
	c++
	java
	java

	c backup
	class & object
	function
	inheritance
	pointer
	polymorphism
	constructor
	data hiding
	fms


*/